### ISSUE TITLE
Slow to batch create new content entries

### ISSUE THREAD

**Issue by rngadam** [contentful/contentful-database-importer.rb#1]
I have a view in PostgreSQL with a 1000 rows with 6 fields.

Creating the entries seems to occur at about 1s per entry which is about 15 minutes....

Is this expected?

Is there a way to make this faster?

**Comment by dlitvakb** [comment]
Hey @rngadam,

Yes, this is expected, as for allowing reference creation without having issues with entry ordering and a few other things, doing a first creation of entry shells, and then populating them after all of them were created as drafts, it takes a little bit of extra time.

Also, there is a sleep behaviour in some specific calls that are done in some cases, for waiting for async events that are happening within Contentful.

I could reduce a little bit of this waiting times and increase the amount of requests for checking the process status, but that would hit hardly on the Rate Limits.

The newest version of the CMA SDK (used by the underlying library `contentful_bootstrap`) solves this issue already, but `contentful_bootstrap` is running on a previous version which is incompatible with the newer one. Upgrading to the newer one is definitely something I'm currently considering, and this would solve the rate limiting issue by automatically backing off when needed, instead of doing some safety back off manually.

Hope that helps

Cheers

**Comment by rngadam** [comment]
Thanks, will try to use the CMA SDK directly then. Maybe if we stick to incremental delta updates between the relational database and contentful this could be acceptable. Which language platform is fastest?

**Comment by dlitvakb** [comment]
Hey @rngadam,

The Ruby CMA SDK, as I mentioned above automatically handles Rate Limit Backoff and can be used directly.

The JS one is having it implemented as we speak, with a release in the next few days.

Hope that helps,

Cheers
